name: Generate and Upload Launch Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - wiki/**
      - .github/workflows/generate-docs.yml

concurrency:
  group: generate-docs
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Clone and install arcscfg
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/csun-arcs/arcscfg.git
          pip install ./arcscfg

      - name: Install dependencies with arcscfg
        run: |
          arcscfg -d install -id -rd jazzy -df cohort_ros2_jazzy_ubuntu_noble.yaml

      - name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        env:
          PYTHONWARNINGS: "ignore:easy_install command is deprecated,ignore:setup.py install is deprecated"
          # SETUPTOOLS_USE_DISTUTILS: stdlib
        with:
          package-name: ${{ github.event.repository.name }}
          target-ros2-distro: jazzy
          skip-tests: true
          no-symlink-install: true

      - name: Generate launch docs
        shell: bash
        run: |
          source ros_ws/install/setup.bash
          GENERATE_LAUNCH_DOCS_SCRIPT=$(find ros_ws/src -type f -name generate_launch_docs.py | head -n1)
          echo "Found script: $GENERATE_LAUNCH_DOCS_SCRIPT"
          python3 "$GENERATE_LAUNCH_DOCS_SCRIPT"

      - name: Debug launch_docs folder
        run: |
          ls -lah ros_ws/launch_docs || echo "No docs generated"

      - name: Move generated docs to wiki directory
        run: |
          mkdir -p wiki/launch_args
          cp ros_ws/launch_docs/*.md wiki/launch_args/

      - name: Create wiki launch files page
        run: |
          echo "# ${{ github.event.repository.name }} Launch Files" > wiki/Launchers.md
          echo "" >> wiki/Launchers.md
          for f in wiki/launch_args/*.md; do
            fname=$(basename "$f" .md)
            echo "- [[launch_args/${fname}]]" >> wiki/Launchers.md
          done

      - name: Publish to GitHub Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki/
