name: Generate and Upload Launch Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - wiki/**
      - .github/workflows/generate-docs.yml

concurrency:
  group: generate-docs
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Clone and install arcscfg
        run: |
          git clone https://github.com/csun-arcs/arcscfg.git
          pip install -e ./arcscfg

      - name: Install dependencies with arcscfg
        run: |
          arcscfg -d -v debug install -id -rd jazzy -df cohort_ros2_jazzy_ubuntu_noble.yaml

      - name: Setup workspace with arcscfg
        run: |
          arcscfg -d -v debug setup -wc cohort_jazzy.yaml -w ros_ws -t https

      - name: Debug directory tree
        run: |
          find .

      - name: Build workspace with arcscfg
        run: |
          source /opt/ros/jazzy/setup.bash
          arcscfg -d -v debug build -w ros_ws -u /opt/ros/jazzy -bs no_cuda

      - name: Generate launch docs
        shell: bash
        run: |
          source ros_ws/install/setup.bash
          set -euo pipefail
          python3 "./ros_ws/src/${{ github.event.repository.name }}/scripts/generate_launch_docs.py" \
            --workspace "${GITHUB_WORKSPACE}/ros_ws" \
            --package-name "${{ github.event.repository.name }}"

      - name: Debug launch_docs folder
        run: |
          echo "[INFO] Launch docs generated:"
          ls -lah ros_ws/launch_docs || echo "No docs found"

      - name: Clone GitHub Wiki
        run: |
          git clone "https://github.com/${{ github.repository }}.wiki.git" wiki

      - name: Move generated docs to wiki directory
        run: |
          set -euo pipefail
          mkdir -p wiki/launch_args
          cp ./ros_ws/launch_docs/*.md wiki/launch_args/

      - name: Render Home.md from template
        run: |
          set -euo pipefail
          pip install jinja2
          python3 "./ros_ws/src/${{ github.event.repository.name }}/scripts/generate_template_md.py" \
            --template-dir "wiki" \
            --template-name "Home.template.md" \
            --output "wiki/Home.md" \
            --launch-docs-dir "ros_ws/launch_docs" \
            --package-name "${{ github.event.repository.name }}"

      - name: Publish to GitHub Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki/
